apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
spec:
  containers:
  - name: mongo-container
    image: mongo
    ports:
    - containerPort: 8081
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: $(DATABASE_MONGO_USER)
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: $(DATABASE_MONGO_PASSWORD)
    envFrom:
      - configMapRef:
          name: delivery-configmap
---

apiVersion: v1
kind: Service
metadata:
   name: mongodb-svc
spec:
   selector:
     app: mongodb-pod
   ports:
     - protocol: TCP
       port: 8081
       targetPort: 8081
