apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-order
  labels:
    app: microservice-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-order
  template:
    metadata:
      name: microservice-order
      labels:
        app: microservice-order
    spec:
      containers:
        - name: microservice-order-container
          image: fagnervalente/postech-soat-order-api
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: delivery-configmap
          resources:
            requests:
              cpu: 250m