apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-product
  labels:
    app: microservice-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-product
  template:
    metadata:
      name: microservice-product
      labels:
        app: microservice-product
    spec:
      containers:
        - name: microservice-product-container
          image: fagnervalente/postech-soat-product-api
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: delivery-configmap
          resources:
            requests:
              cpu: 250m