apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-payment
  labels:
    app: microservice-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-payment
  template:
    metadata:
      name: microservice-payment
      labels:
        app: microservice-payment
    spec:
      containers:
        - name: microservice-payment-container
          image: fagnervalente/postech-soat-payment-api
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: delivery-configmap
          resources:
            requests:
              cpu: 250m