apiVersion: v1
kind: Service
metadata:
  name: svc-microservice-order
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3010
      targetPort: 3000
  selector:
    app: microservice-order