apiVersion: v1
kind: Service
metadata:
  name: svc-microservice-product
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: microservice-product